LightBlog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.contrib import admin
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:page>/', views.view, name='view'),
    path('article/<int:article_id>', views.Article, name='article'),
    path('about', views.about, name='about'),
    path('study', views.study, name='study'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class admin_user(models.Model):
    admin_user_id = models.AutoField(primary_key=True)
    user = models.CharField(max_length=50)
    head = models.ImageField()
    password = models.CharField(max_length=100)
    email = models.EmailField()

class user(models.Model):
    user_id = models.AutoField(primary_key=True)
    user = models.CharField(max_length=50)
    head = models.ImageField()
    password = models.CharField(max_length=100)
    email = models.EmailField()

class article(models.Model):
    article_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=140)
    subtitle = models.CharField(max_length=140)
    content = models.TextField(default="")
    synopsis = models.CharField(max_length=140,default="")
    time = models.DateTimeField()
    likes = models.BigIntegerField(default=0)
    public = models.BooleanField(default=True)
    reviews = models.BigIntegerField(default=0)
    image = models.ImageField(upload_to='img')

    def __str__(self):
        return self.title

class review(models.Model):
    review_id = models.AutoField(primary_key=True)
    article_id = models.ForeignKey(article, on_delete=models.CASCADE)
    nick = models.CharField(max_length=50)
    content = models.TextField()
    time = models.DateTimeField()
    public = models.BooleanField(default=True)

    def __str__(self):
        return self.content

class reply(models.Model):
    reply_id = models.AutoField(primary_key=True)
    review_id = models.ForeignKey(review, on_delete=models.CASCADE)
    content = models.TextField()
    time = models.DateTimeField()
    public = models.BooleanField(default=True)

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from . import models

# Create your views here.

def index(request):
    check = models.article.objects.order_by('article_id')[5:10]
    next = str('')
    previous = str('disabled')
    if len(check) == 0:
        next = 'disabled'
    articles = models.article.objects.order_by('article_id')[:5]
    page = 1
    context = {'articles':articles,'previous':previous,'next':next,'nextpage':page+1,'prepage':page-1}
    return render(request, 'index.html', context)

def view(request,page):
    check = models.article.objects.order_by('article_id')[5*page:5*(page+1)]
    next = str('')
    previous = str('')
    if len(check) == 0:
        next = 'disabled'
    if page <= 1:
        previous = 'disabled'
    articles = models.article.objects.order_by('article_id')[5*(page-1):5*page]
    context = {'articles':articles,'previous':previous,'next':next,'nextpage':page+1,'prepage':page-1}
    return render(request, 'index.html', context)

def Article(request, article_id):
    article = models.article.objects.get(pk=article_id)
    context = {'article':article}
    return render(request, 'article.html',context)

def about(request):
    return render(request, 'about.html')

def study(request):
    return render(request, 'study.html')

blog/templates/about.html
{% extends "./index.html" %}
{% load static %}
{% block main %}
<div id = "main">
    <article class="post">
        <header>
            <div class="title">
                <h2>关于</h2>
            </div>
        </header>
        <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
        <footer>
            <ul class="actions">
            </ul>
            <ul class="stats">
                <li><a href="#">General</a></li>
                <li><a href="#" class="icon fa-heart">28</a></li>
                <li><a href="#" class="icon fa-comment">128</a></li>
            </ul>
        </footer>
    </article>
</div>
{% endblock %}
{% block sidebar %}
{% endblock %}

blog/templates/article.html
{% extends "./index.html" %}
{% load static %}
{% block main %}
<div id = "main">
    <article class="post">
        <header>
            <div class="title">
                <h2><a href="#">{{ article.title }}</a></h2>
                <p>{{ article.subtitle }}</p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01">{{article.time}}</time>
                <a href="#" class="author"><span class="name">xiepingfu</span><img src="{% static 'images/avatar.jpg' %}" alt="" /></a>
            </div>
        </header>
        <a href="{% url 'blog:article' article.article_id %}" class="image featured"><img src="{{article.image.url}}" alt="" /></a>
            <dvi>
            {{article.content}}
            </dvi>
        <footer>
            <ul class="actions">

            </ul>
            <ul class="stats">
                <li><a href="#" class="icon fa-heart">{{article.likes}}</a></li>
                <li><a href="#" class="icon fa-comment">{{article.reviews}}</a></li>
            </ul>
        </footer>
    </article>
</div>
{% endblock %}
{% block sidebar %}
{% endblock %}

blog/templates/study.html
{% extends "./index.html" %}
{% block sidebar %}
{% endblock %}